### PR TITLE
Organizated game

### PR DESCRIPTION
**Pull request by achechi15**
My task was to move all the global variables to inside of the GAME_ object, in order to improve the performance of the game and to easier readability.

Pd: srry for making 2 commits, i tried to delete it one commit but the changes keep reverting.

### CODE REVIEW

**Comment by ZhengLinLei** [comment]
Please change the dest branch to `ZhengLinLei:feature_task_change_var`

**Review by ZhengLinLei — APPROVED** [review]

**Comment by ZhengLinLei** [comment]
#57

**Comment by achechi15** [comment]
heard

**Comment by achechi15** [comment]
> #57

heard

**Comment by hoodrichpirobo** [comment]
dale alexisss

**Pull request merged**
